<?php

namespace SchoolWeb;

use Illuminate\Database\Eloquent\Model as BaseModel;
use Illuminate\Support\Str;
use PhpParser\Node\Scalar\String_;

class Model extends BaseModel
{
    public $incrementing = false;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model){
            @$model->{$model->getKeyName()} = (String) Str::uuid();

        });
    }
}
